apiVersion: apps/v1
kind: Deployment
metadata:
  name: docu-swift
  labels:
    app: docu-swift
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: docu-swift
  template:
    metadata:
      labels:
        app: docu-swift
    spec:
      containers:
      - name: docu-swift-container
        image: parasmani1/docu-swift:latest 
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"