apiVersion: v1
kind: Service
metadata:
  name: docu-swift-service
  labels:
    app: docu-swift
spec:
  type: NodePort
  selector:
    app: docu-swift
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001